from arriendo.services import *

# Tipos de usuarios
user_type_1 = create_user_type('Propietario')
user_type_2 = create_user_type('Arrendador')

# Tipos de vivienda
casa = create_house_type('Casa')
departamento = create_house_type('Departamento')
parcela = create_house_type('Parcela')

# Estados contrato
solicitado = create_status('solicitado')
aceptado = create_status('aceptado')
rechazado = create_status('rechazado')

# Crear regiones
add_region('Arica y Parinacota')
add_region('Tarapacá')
add_region('Antofagasta')
add_region('Atacama')
add_region('Coquimbo')
add_region('Valparaíso')
add_region('Región del Libertador Gral. Bernardo O’Higgins')
add_region('Región del Maule')
add_region('Región del Biobío')
add_region('Región de la Araucanía')
add_region('Región de Los Ríos')
add_region('Región de Los Lagos')
add_region('Región Aisén del Gral. Carlos Ibáñez del Campo')
add_region('Región de Magallanes y de la Antártica Chilena')
add_region('Región Metropolitana de Santiago')

# Agregar comunas
add_commune('Arica', 1)
add_commune('Camarones', 1)
add_commune('Putre', 1)
add_commune('General Lagos', 1)
add_commune('Iquique', 2)
add_commune('Alto Hospicio', 2)
add_commune('Pozo Almonte', 2)
add_commune('Camiña', 2)
add_commune('Colchane', 2)
add_commune('Huara', 2)
add_commune('Pica', 2)
add_commune('Antofagasta', 3)
add_commune('Mejillones', 3)
add_commune('Sierra Gorda', 3)
add_commune('Taltal', 3)
add_commune('Calama', 3)
add_commune('Ollagüe', 3)
add_commune('San Pedro de Atacama', 3)
add_commune('Tocopilla', 3)
add_commune('María Elena', 3)
add_commune('Copiapó', 4)
add_commune('Caldera', 4)
add_commune('Tierra Amarilla', 4)
add_commune('Chañaral', 4)
add_commune('Diego de Almagro', 4)
add_commune('Vallenar', 4)
add_commune('Alto del Carmen', 4)
add_commune('Freirina', 4)
add_commune('Huasco', 4)
add_commune('La Serena', 5)
add_commune('Coquimbo', 5)
add_commune('Andacollo', 5)
add_commune('La Higuera', 5)
add_commune('Paiguano', 5)
add_commune('Vicuña', 5)
add_commune('Illapel', 5)
add_commune('Canela', 5)
add_commune('Los Vilos', 5)
add_commune('Salamanca', 5)
add_commune('Ovalle', 5)
add_commune('Combarbalá', 5)
add_commune('Monte Patria', 5)
add_commune('Punitaqui', 5)
add_commune('Río Hurtado', 5)
add_commune('Valparaíso', 6)
add_commune('Casablanca', 6)
add_commune('Concón', 6)
add_commune('Juan Fernández', 6)
add_commune('Puchuncaví', 6)
add_commune('Quintero', 6)
add_commune('Viña del Mar', 6)
add_commune('Isla de Pascua', 6)
add_commune('Los Andes', 6)
add_commune('Calle Larga', 6)
add_commune('Rinconada', 6)
add_commune('San Esteban', 6)
add_commune('La Ligua', 6)
add_commune('Cabildo', 6)
add_commune('Papudo', 6)
add_commune('Petorca', 6)
add_commune('Zapallar', 6)
add_commune('Quillota', 6)
add_commune('Calera', 6)
add_commune('Hijuelas', 6)
add_commune('La Cruz', 6)
add_commune('Nogales', 6)
add_commune('San Antonio', 6)
add_commune('Algarrobo', 6)
add_commune('Cartagena', 6)
add_commune('El Quisco', 6)
add_commune('El Tabo', 6)
add_commune('Santo Domingo', 6)
add_commune('San Felipe', 6)
add_commune('Catemu', 6)
add_commune('Llaillay', 6)
add_commune('Panquehue', 6)
add_commune('Putaendo', 6)
add_commune('Santa María', 6)
add_commune('Quilpué', 6)
add_commune('Limache', 6)
add_commune('Olmué', 6)
add_commune('Villa Alemana', 6)
add_commune('Rancagua', 7)
add_commune('Codegua', 7)
add_commune('Coinco', 7)
add_commune('Coltauco', 7)
add_commune('Doñihue', 7)
add_commune('Graneros', 7)
add_commune('Las Cabras', 7)
add_commune('Machalí', 7)
add_commune('Malloa', 7)
add_commune('Mostazal', 7)
add_commune('Olivar', 7)
add_commune('Peumo', 7)
add_commune('Pichidegua', 7)
add_commune('Quinta de Tilcoco', 7)
add_commune('Rengo', 7)
add_commune('Requínoa', 7)
add_commune('San Vicente', 7)
add_commune('Pichilemu', 7)
add_commune('La Estrella', 7)
add_commune('Litueche', 7)
add_commune('Marchihue', 7)
add_commune('Navidad', 7)
add_commune('Paredones', 7)
add_commune('San Fernando', 7)
add_commune('Chépica', 7)
add_commune('Chimbarongo', 7)
add_commune('Lolol', 7)
add_commune('Nancagua', 7)
add_commune('Palmilla', 7)
add_commune('Peralillo', 7)
add_commune('Placilla', 7)
add_commune('Pumanque', 7)
add_commune('Santa Cruz', 7)
add_commune('Talca', 8)
add_commune('Constitución', 8)
add_commune('Curepto', 8)
add_commune('Empedrado', 8)
add_commune('Maule', 8)
add_commune('Pelarco', 8)
add_commune('Pencahue', 8)
add_commune('Río Claro', 8)
add_commune('San Clemente', 8)
add_commune('San Rafael', 8)
add_commune('Cauquenes', 8)
add_commune('Chanco', 8)
add_commune('Pelluhue', 8)
add_commune('Curicó', 8)
add_commune('Hualañé', 8)
add_commune('Licantén', 8)
add_commune('Molina', 8)
add_commune('Rauco', 8)
add_commune('Romeral', 8)
add_commune('Sagrada Familia', 8)
add_commune('Teno', 8)
add_commune('Vichuquén', 8)
add_commune('Linares', 8)
add_commune('Colbún', 8)
add_commune('Longaví', 8)
add_commune('Parral', 8)
add_commune('Retiro', 8)
add_commune('San Javier', 8)
add_commune('Villa Alegre', 8)
add_commune('Yerbas Buenas', 8)
add_commune('Concepción', 9)
add_commune('Coronel', 9)
add_commune('Chiguayante', 9)
add_commune('Florida', 9)
add_commune('Hualqui', 9)
add_commune('Lota', 9)
add_commune('Penco', 9)
add_commune('San Pedro de la Paz', 9)
add_commune('Santa Juana', 9)
add_commune('Talcahuano', 9)
add_commune('Tomé', 9)
add_commune('Hualpén', 9)
add_commune('Lebu', 9)
add_commune('Arauco', 9)
add_commune('Cañete', 9)
add_commune('Contulmo', 9)
add_commune('Curanilahue', 9)
add_commune('Los Álamos', 9)
add_commune('Tirúa', 9)
add_commune('Los Ángeles', 9)
add_commune('Antuco', 9)
add_commune('Cabrero', 9)
add_commune('Laja', 9)
add_commune('Mulchén', 9)
add_commune('Nacimiento', 9)
add_commune('Negrete', 9)
add_commune('Quilaco', 9)
add_commune('Quilleco', 9)
add_commune('San Rosendo', 9)
add_commune('Santa Bárbara', 9)
add_commune('Tucapel', 9)
add_commune('Yumbel', 9)
add_commune('Alto Biobío', 9)
add_commune('Chillán', 9)
add_commune('Bulnes', 9)
add_commune('Cobquecura', 9)
add_commune('Coelemu', 9)
add_commune('Coihueco', 9)
add_commune('Chillán Viejo', 9)
add_commune('El Carmen', 9)
add_commune('Ninhue', 9)
add_commune('Ñiquén', 9)
add_commune('Pemuco', 9)
add_commune('Pinto', 9)
add_commune('Portezuelo', 9)
add_commune('Quillón', 9)
add_commune('Quirihue', 9)
add_commune('Ránquil', 9)
add_commune('San Carlos', 9)
add_commune('San Fabián', 9)
add_commune('San Ignacio', 9)
add_commune('San Nicolás', 9)
add_commune('Treguaco', 9)
add_commune('Yungay', 9)
add_commune('Temuco', 10)
add_commune('Carahue', 10)
add_commune('Cunco', 10)
add_commune('Curarrehue', 10)
add_commune('Freire', 10)
add_commune('Galvarino', 10)
add_commune('Gorbea', 10)
add_commune('Lautaro', 10)
add_commune('Loncoche', 10)
add_commune('Melipeuco', 10)
add_commune('Nueva Imperial', 10)
add_commune('Padre las Casas', 10)
add_commune('Perquenco', 10)
add_commune('Pitrufquén', 10)
add_commune('Pucón', 10)
add_commune('Saavedra', 10)
add_commune('Teodoro Schmidt', 10)
add_commune('Toltén', 10)
add_commune('Vilcún', 10)
add_commune('Villarrica', 10)
add_commune('Cholchol', 10)
add_commune('Angol', 10)
add_commune('Collipulli', 10)
add_commune('Curacautín', 10)
add_commune('Ercilla', 10)
add_commune('Lonquimay', 10)
add_commune('Los Sauces', 10)
add_commune('Lumaco', 10)
add_commune('Purén', 10)
add_commune('Renaico', 10)
add_commune('Traiguén', 10)
add_commune('Victoria', 10)
add_commune('Valdivia', 11)
add_commune('Corral', 11)
add_commune('Lanco', 11)
add_commune('Los Lagos', 11)
add_commune('Máfil', 11)
add_commune('Mariquina', 11)
add_commune('Paillaco', 11)
add_commune('Panguipulli', 11)
add_commune('La Unión', 11)
add_commune('Futrono', 11)
add_commune('Lago Ranco', 11)
add_commune('Río Bueno', 11)
add_commune('Puerto Montt', 12)
add_commune('Calbuco', 12)
add_commune('Cochamó', 12)
add_commune('Fresia', 12)
add_commune('FruVllar', 12)
add_commune('Los Muermos', 12)
add_commune('Llanquihue', 12)
add_commune('Maullín', 12)
add_commune('Puerto Varas', 12)
add_commune('Castro', 12)
add_commune('Ancud', 12)
add_commune('Chonchi', 12)
add_commune('Curaco de Vélez', 12)
add_commune('Dalcahue', 12)
add_commune('Puqueldón', 12)
add_commune('Queilén', 12)
add_commune('Quellón', 12)
add_commune('Quemchi', 12)
add_commune('Quinchao', 12)
add_commune('Osorno', 12)
add_commune('Puerto Octay', 12)
add_commune('Purranque', 12)
add_commune('Puyehue', 12)
add_commune('Río Negro', 12)
add_commune('San Juan de la Costa', 12)
add_commune('San Pablo', 12)
add_commune('Chaitén', 12)
add_commune('Futaleufú', 12)
add_commune('Hualaihué', 12)
add_commune('Palena', 12)
add_commune('Coihaique', 13)
add_commune('Lago Verde', 13)
add_commune('Aisén', 13)
add_commune('Cisnes', 13)
add_commune('Guaitecas', 13)
add_commune('Cochrane', 13)
add_commune('O’Higgins', 13)
add_commune('Tortel', 13)
add_commune('Chile Chico', 13)
add_commune('Río Ibáñez', 13)
add_commune('Punta Arenas', 14)
add_commune('Laguna Blanca', 14)
add_commune('Río Verde', 14)
add_commune('San Gregorio', 14)
add_commune('Cabo de Hornos (Ex Navarino)', 14)
add_commune('Antártica', 14)
add_commune('Porvenir', 14)
add_commune('Primavera', 14)
add_commune('Timaukel', 14)
add_commune('Natales', 14)
add_commune('Torres del Paine', 14)
add_commune('Cerrillos', 15)
add_commune('Cerro Navia', 15)
add_commune('Conchalí', 15)
add_commune('El Bosque', 15)
add_commune('Estación Central', 15)
add_commune('Huechuraba', 15)
add_commune('Independencia', 15)
add_commune('La Cisterna', 15)
add_commune('La Florida', 15)
add_commune('La Granja', 15)
add_commune('La Pintana', 15)
add_commune('La Reina', 15)
add_commune('Las Condes', 15)
add_commune('Lo Barnechea', 15)
add_commune('Lo Espejo', 15)
add_commune('Lo Prado', 15)
add_commune('Macul', 15)
add_commune('Maipú', 15)
add_commune('Ñuñoa', 15)
add_commune('Pedro Aguirre Cerda', 15)
add_commune('Peñalolén', 15)
add_commune('Providencia', 15)
add_commune('Pudahuel', 15)
add_commune('Quilicura', 15)
add_commune('Quinta Normal', 15)
add_commune('Recoleta', 15)
add_commune('Renca', 15)
add_commune('San Joaquín', 15)
add_commune('San Miguel', 15)
add_commune('San Ramón', 15)
add_commune('Santiago centro', 15)
add_commune('Vitacura', 15)
add_commune('Puente Alto', 15)
add_commune('Pirque', 15)
add_commune('San José de Maipo', 15)
add_commune('Colina', 15)
add_commune('Lampa', 15)
add_commune('Tiltil', 15)
add_commune('San Bernardo', 15)
add_commune('Buin', 15)
add_commune('Calera de Tango', 15)
add_commune('Paine', 15)
add_commune('Melipilla', 15)
add_commune('Alhué', 15)
add_commune('Curacaví', 15)
add_commune('María Pinto', 15)
add_commune('San Pedro', 15)
add_commune('Talagante', 15)
add_commune('El Monte', 15)
add_commune('Isla de Maipo', 15)
add_commune('Padre Hurtado', 15)
add_commune('Peñaflor', 15)

# Crear usuarios
dueno = create_user('188888888', 'Leslie', '', 'Reyes', 'Villalobos', 'Vicuña Mackenna 2020', '+56999999999', 'leslie@mail.com', user_type_1.id, '123456lil')
arrendatario = create_user('199999999', 'Gonzalo', 'Andrés', 'Gangas', 'Segura', 'Macul 15987', '+56999999999', 'gonzalo@mail.com', user_type_2.id, '123456lil')

# Crear propiedad
propiedad = create_property('Casa 1', 'Linda casa ubicada a pasos del metro', 60, 80, 1, 2, 2, 'Walker Martinez 3032', 300, casa.id, 600000, dueno.rut)

# Actualizar propiedad
update_property(propiedad.id, 'Casa 1', 'Linda casa ubicada a pasos del metro', 60, 80, 1, 2, 2, 'Walker Martinez 3032', 300, casa.id, 700000)

# Solicitar propiedad
solicitud = request_property(propiedad.id, arrendatario.rut, solicitado.name)

# Rechazar solicitud
update_status(solicitud.id, rechazado.name)

## Eliminar propiedad
delete_property(propiedad.id)